### ISSUE TITLE
Blank screen when running in remote ssh window

### ISSUE THREAD

**Issue by joostn** [rpdswtk/vsmqtt#62]
Hi,

I think a VS code update broke things again. When I click one of the profiles, just a blank screen is opened. I've tried two different computers.

**Comment by rpdswtk** [comment]
I can't reproduce the issue. Can you send me some details? I'm on windows 10 vscode: 1.58.

**Comment by joostn** [comment]
Ah sorry, it seems to be restricted to VSCode remote hosts. I'm connecting to a remote repository on a linux host via Remote+SSH, so I presume the plugin is running on the remote host.

Locally it works fine. So I can use it in a local window, it's not a big deal.

**Comment by DocMoebiuz** [comment]
I experienced issue with Codespaces and using the browser-based VS Code. But at the moment I can say that the extension runs just fine: my local VSCode, VSCode with devContainer and also via Codespaces with local VSCode or using the browser-based VSCode.

Since this issue is over a year old, and all the scenarios above are working (which include the described scenario by @joostn ), this issue could be closed.

**Comment by joostn** [comment]
Yes it's working fine now, sorry for keeping this open!
